### ISSUE TITLE
Support Bitbucket integration

### ISSUE THREAD

**Issue by tdbeattie** [redhat-cop/pelorus#106]
We recently installed Pelorus into a cluster being used on an Open Innovation Labs residency in EMEA. The customer is using Bitbucket as their source code repository and Pelorus is currently unable to collect data from Bitbucket.

Raising this issue to track future development and integration to Bitbucket.

**Comment by themoosman** [comment]
https://developer.atlassian.com/server/bitbucket/how-tos/command-line-rest/#simple-example-of-retrieving-repository-commits

**Comment by etsauer** [comment]
Just to clarify... this should not be a net-new exporter. Instead this should be an enhancement to the existing committime exporter. If anyone is interested in picking this up, we should chat about what this looks like.
