### ISSUE TITLE
Updated MTTR panel graph to round display value of y-axis to 1 decimal point

### ISSUE THREAD

**Issue by prakritiverma** [redhat-cop/pelorus#123]
![image](https://user-images.githubusercontent.com/8949609/86829157-1501f800-c062-11ea-87eb-28b98a0e7384.png)

**Comment by kenwilli** [comment]
@prakritiverma Is there a way to recreate this bug? I'm not seeing this issue on my screen:
![image](https://user-images.githubusercontent.com/48998069/87472502-a7b41100-c5e5-11ea-9d94-c911f144b6c9.png)

I played with date ranges from 24 hours to last 7 days but still looks similar to my screen shot.

**Comment by prakritiverma** [comment]
Maybe try running the demo a few times to change the numbers up? I think during the demo (which we may have a recording of, if that's helpful at all) we ran it twice before it showed that many decimal places...
