### ISSUE TITLE
Change calculation of CFR to use the creation timestamp.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pelorus#141]
As I am working on documentation for how we collect each metric, I noticed that we are currently calculating CFR with this formula:

```
    - record: fr:change_failure_rate
      expr: >
        count(fr:time_to_restore) / count(deploy_timestamp)
```

I wonder if it should instead be 

```
count(failure_creation_timestamp) / count(deploy_timestamp)
```

for counting change failure, we don't really care whether the failure has been resolved do we?

**Comment by prakritiverma** [comment]
Closed by #162
