### ISSUE TITLE
Add a rego/conftest github action for validation of helm chart

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pelorus#148]
I'd like to get some policies in place to ensure that the Pelorus helm chart is following some consistent practices. We've now have `ct` in place to do chart linting, but I'd like to also enforce some best practice type things with rego. Initially i'm thinking of:

* Ensure that no resource definitions include `.metdata.namespace`
* Ensure proper labeling on all resources.
* Enforce some sort of naming scheme to ensure uniqueness on cluster-scoped resources.

@garethahealy is this something you could help us get set up?

**Comment by garethahealy** [comment]
@etsauer ; few questions:

1. other than `storage` and `charts` dir, are there any other YAML/JSON objects? Couldn't see any, so presume not.
2. of the policies mentioned:

a. no namespace: easily do-able.
b. k8s labels: already done - https://github.com/redhat-cop/rego-policies/blob/master/policy/ocp/bestpractices/common-k8s-labels-notset/src.rego
c. unique names: this needs some thought, maybe a chat at next containers-cop. as it might not be that easy, needs thought.

**Comment by etsauer** [comment]
@garethahealy yeah, I don't have anything specific in mind for how to enforcethe third rules yet. However, the use case here is that we want to be able to support multiple deployments of Pelorus in a single cluster. Each deployment involves creating some cluster-level rbac, which we want to make sure doesn't break other deployments when we uninstall them. So the solution is to make sure that the helm templates append something to the name to make each deployment unique.

Also, do we have any examples yet of running policies against helm charts? I assume you'd have to `helm template` them first to just get the yaml.

**Comment by garethahealy** [comment]
@etsauer re: helm; yep, the PR already has that: https://github.com/redhat-cop/pelorus/pull/149 - It uses the below, which is then passed to conftest:
- https://github.com/redhat-cop/bats-library/blob/master/src/helm.bash
