### ISSUE TITLE
Errors reported when running ./runhelm.sh

### ISSUE THREAD

**Issue by jameslabocki** [redhat-cop/pelorus#155]
The I received the following errors when trying to install pelorus:

> [jameslabocki@unknown5c80b6f29ce8 pelorus]$ ./runhelm.sh 
> namespace/pelorus created
> serviceaccount/grafana-operator created
> serviceaccount/prometheus-operator-pelorus created
> serviceaccount/pelorus-prometheus created
> secret/grafana-k8s-proxy created
> secret/prometheus-pelorus-htpasswd created
> secret/additional-scrape-configs created
> configmap/pelorus-sdm created
> configmap/trusted-certs created
> customresourcedefinition.apiextensions.k8s.io/grafanas.integreatly.org created
> customresourcedefinition.apiextensions.k8s.io/grafanadashboards.integreatly.org created
> customresourcedefinition.apiextensions.k8s.io/grafanadatasources.integreatly.org created
> clusterrole.rbac.authorization.k8s.io/grafana-proxy created
> clusterrole.rbac.authorization.k8s.io/prometheus-mdt-oauth-clusterrole created
> clusterrole.rbac.authorization.k8s.io/prometheus-operator-pelorus created
> clusterrole.rbac.authorization.k8s.io/pelorus-prometheus created
> clusterrolebinding.authorization.openshift.io/pelorus-grafana-proxy created
> clusterrolebinding.rbac.authorization.k8s.io/pelorus-prometheus-mdt-oauth-crb created
> clusterrolebinding.rbac.authorization.k8s.io/pelorus-prometheus-operator-pelorus created
> clusterrolebinding.rbac.authorization.k8s.io/pelorus-pelorus-prometheus created
> role.rbac.authorization.k8s.io/grafana-operator created
> rolebinding.rbac.authorization.k8s.io/grafana-operator created
> service/prometheus-operator-pelorus created
> service/prometheus-pelorus created
> deployment.apps/grafana-operator created
> deployment.apps/prometheus-operator-pelorus created
> prometheus.monitoring.coreos.com/prometheus-pelorus created
> prometheusrule.monitoring.coreos.com/pelorus created
> route.route.openshift.io/prometheus-pelorus created
> unable to recognize "STDIN": no matches for kind "Grafana" in version "integreatly.org/v1alpha1"
> unable to recognize "STDIN": no matches for kind "GrafanaDashboard" in version "integreatly.org/v1alpha1"
> unable to recognize "STDIN": no matches for kind "GrafanaDataSource" in version "integreatly.org/v1alpha1"
> Error in template processing and application!
> 
> [jameslabocki@unknown5c80b6f29ce8 pelorus]$ helm version
> version.BuildInfo{Version:"v3.3.0-rc.2", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
> 
> [jameslabocki@unknown5c80b6f29ce8 pelorus]$ jq --version
> jq-1.6
> 
> [jameslabocki@unknown5c80b6f29ce8 pelorus]$ oc version
> Client Version: 4.5.3
> Server Version: 4.5.3
> Kubernetes Version: v1.18.3+3107688

**Comment by themoosman** [comment]
@jameslabocki What version of OCP are you using?  Also, are you running this as a `cluster-admin`?

**Comment by jameslabocki** [comment]
```
[jameslabocki@unknown5c80b6f29ce8 pelorus]$ oc version
Client Version: 4.5.3
Server Version: 4.5.3
Kubernetes Version: v1.18.3+3107688
```

```
$ oc whoami
system:admin
```

**Comment by themoosman** [comment]
I don't know if that version of OCP will support the Grafana 3.0.2 Operator.  

https://github.com/redhat-cop/pelorus/commit/499a7cc788ea5c57ae2ef97037f08b2b70d93a5e#diff-02cbabf2ec0ee7b2faff1fc0232e1fc4

**Comment by etsauer** [comment]
For now, the workaround is just to run the `./runhelm.sh` command a second time. There is a race condition where the CRDs may not be completely applied when we try to invoke the APIs. Longer term, #153 provides a new "scriptless" install method that won't have this problem.

**Comment by etsauer** [comment]
@jameslabocki now that #153 has been merged, you may need to just re-test from scratch as lot of this changes.

**Comment by etsauer** [comment]
@jameslabocki did you ever get a chance to try the latest?

**Comment by etsauer** [comment]
closing to due inactivity.
