### ISSUE TITLE
Issues found testing release candidate v1.2.1-rc

### ISSUE THREAD

**Issue by malacourse** [redhat-cop/pelorus#166]
-- Doc Issue
In the configuration docs section there is an invalid path for the chart
helm upgrade pelorus charts/deploy --namespace pelorus --values myclusterconfigs/pelorus/values.yaml
should be:
helm upgrade pelorus charts/pelorus --namespace pelorus --values myclusterconfigs/pelorus/values.yaml

-- Doc Issue
The commit time exporter has a sample for the values.yaml configuration.  The other two should have the same.  Could we add a Copy link similar to how OCP docs do it?

-- Doc issues
pelorus/docs/Development.md - invalid link 
Set any environment variables required (or desired) for the given exporter (see **Configuring Exporters** to see supported variables).

**Comment by prakritiverma** [comment]
Resolved in v1.2.1
