### ISSUE TITLE
unable to get deployment frequency metric when using external Registry

### ISSUE THREAD

**Issue by ChrystianDuarte** [redhat-cop/pelorus#176]
we are using 

- Pelorus branch master

i am using  this demo:

https://github.com/siamaksade/openshift-cd-demo

and we try to use Pelorus to get metrics.

Expected result
- Dashboard showing the metrics of deployments

Actual Result
- the dashboard not show the metrics and the deploytime-exporter pod show the following log

08-27-2020 17:35:31 DEBUG    Skipping unresolved image reference: quay.io/cduarter/tasks-app:latest
08-27-2020 17:35:31 DEBUG    Skipping unresolved image reference: quay.io/cduarter/tasks-app:latest
08-27-2020 17:35:31 DEBUG    Skipping unresolved image reference: quay.io/cduarter/tasks-app:latest
08-27-2020 17:35:31 DEBUG    Skipping unresolved image reference: quay.io/cduarter/tasks-app:latest
08-27-2020 17:35:31 DEBUG    Skipping unresolved image reference: quay.io/cduarter/tasks-app:latest
08-27-2020 17:35:31 DEBUG    Skipping unresolved image reference: quay.io/cduarter/tasks-app:latest
08-27-2020 17:35:31 DEBUG    Skipping unresolved image reference: quay.io/cduarter/tasks-app:stage
08-27-2020 17:35:31 DEBUG    Skipping unresolved image reference: quay.io/cduarter/tasks-app:stage
Watching namespaces: ['dev-opentlc', 'stage-opentlc']

ANALISYS

I think that i am using a external registry and the exported does not find an image registry.
how  pelorus  should work when using an external registry?  

![Captura de pantalla de 2020-08-27 13-42-49](https://user-images.githubusercontent.com/19255861/91477507-70838180-e86c-11ea-87f6-9e06d82f7b31.png)
![Captura de pantalla de 2020-08-27 13-52-14](https://user-images.githubusercontent.com/19255861/91477577-8a24c900-e86c-11ea-84ea-eea76597eb9e.png)

**Comment by etsauer** [comment]
@ChrystianDuarte can you provide a sample of the Deployment/DeploymentConfig that's using this image?

**Comment by ChrystianDuarte** [comment]
hello guys,

the deployment config is:

kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  selfLink: /apis/apps.openshift.io/v1/namespaces/dev-opentlc/deploymentconfigs/tasks
  resourceVersion: '1437414'
  name: tasks
  uid: 598bcbba-d63f-474c-ba53-fa98ee2dd5e6
  creationTimestamp: '2020-08-25T19:43:00Z'
  generation: 13
  namespace: dev-opentlc
  labels:
    app: tasks
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers: []
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: tasks
    deploymentconfig: tasks
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tasks
        deploymentconfig: tasks
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /ws/demo/healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: /dev/termination-log
          name: tasks
          livenessProbe:
            httpGet:
              path: /ws/demo/healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'quay.io/cduarter/tasks-app:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 13
  details:
    message: manual change
    causes:
      - type: Manual
  availableReplicas: 1
  unavailableReplicas: 0
  latestVersion: 9
  updatedReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-09-02T13:36:46Z'
      lastTransitionTime: '2020-09-02T13:36:46Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-09-02T14:03:30Z'
      lastTransitionTime: '2020-09-02T14:03:27Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "tasks-9" successfully rolled out
  replicas: 1
  readyReplicas: 1

**Comment by etsauer** [comment]
@ChrystianDuarte thanks. Could you also provide a ReplicationController YAML for the latest rollout?

**Comment by ChrystianDuarte** [comment]
guys,

I attach the all objects of my namespace pelorus

[pelorus-objects.zip](https://github.com/redhat-cop/pelorus/files/5169580/pelorus-objects.zip)

Thanks

**Comment by etsauer** [comment]
hey @ChrystianDuarte I wasn't asking to see the Pelorus deployment info, but the info about the application that you've cited that's being "skipped". The deploytime exporter is looking to key off of the `sha256` hash in the `image` field of a ReplicationController, or ReplicaSet, so what I'm looking for is an example of the ReplicationController you'd find at:

```
oc get replicationcontroller -l deploymentconfig=tasks -n dev-opentlc -o yaml
```

**Comment by ChrystianDuarte** [comment]
hey @etsauer  

when I execute you command the output is 

[cduarte@ronnie pelorus]$ oc get replicationcontroller -l deploymentconfig=tasks -n dev-opentlc -o yaml
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

but the replication controllers of the namespaces of dev-opentlc are the following:

[cduarte@ronnie pelorus]$ oc get rc -n dev-opentlc 
NAME      DESIRED   CURRENT   READY   AGE
tasks-1   0         0         0       8d
tasks-2   0         0         0       8d
tasks-3   0         0         0       8d
tasks-4   0         0         0       7d1h
tasks-5   0         0         0       6d23h
tasks-6   0         0         0       6d23h
tasks-7   0         0         0       6d21h
tasks-8   0         0         0       6d19h
tasks-9   1         1         1       26h

I attach the last , task-9

[rc-task-9.zip](https://github.com/redhat-cop/pelorus/files/5170035/rc-task-9.zip)

**Comment by etsauer** [comment]
ok, I've taken a look, and I believe you're right. There is probably a better way for us to get the ImageIDs for this case. I'll mark this as a bug, and we can get to work on that.

**Comment by etsauer** [comment]
Closing. Assumed complete.
