### ISSUE TITLE
Gitlab project search by name sometimes picks incorrect project

### ISSUE THREAD

**Issue by willowmck** [redhat-cop/pelorus#212]
The following code block will default to the first project in the list.  This sometimes provides the wrong project.  
https://github.com/redhat-cop/pelorus/blob/master/exporters/committime/collector_gitlab.py#L36-L38

As an example, a search for '**leia**' returned project '**frontend_nelson_quileia**'.

**Comment by themoosman** [comment]
Fixed by #209
