### ISSUE TITLE
Lead Time exporter should pull git repo information from BuildConfigs

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pelorus#28]
Currently the lead time exporter requires an administrator to pass a comma-separated list of git repos representing application source code via environment variable to the lead time exporter. This doesn't scale well, as we would have to make an administrative change for each application that comes on board. 

What we should do instead is grab the git repository information from the `BuildConfigs` we find in the cluster.

**Comment by etsauer** [comment]
@AlyIbrahim what do you think?

**Comment by AlyIbrahim** [comment]
@etsauer 
The comma separate git repos was required for the initial commit-exporter
For leadtime-exporter, comma separated project list is "optionally" needed and git repos information is pulled from BuildConfigs as required, if not provided the exporter will pull projects that belongs to user.
Check #20 description and let me know if I miss your point
