### ISSUE TITLE
Refactor documentation to account for Pelorus name change.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pelorus#32]

**Comment by sbailleu** [comment]
Metric Driven Transformation / mdt / quickstart.. should not appear anymore in the code. Pelorus should appear. 
Different types of docs:
- Read me, main page
- Contribution guide
> How to build an exporter?
> How to configure Pelorus?
...
Example of contribution guide: https://github.com/redhat-cop/uncontained.io/blob/master/CONTRIBUTING.adoc
