### ISSUE TITLE
Include graph showing 30, 60 day (or more) history for each?

### ISSUE THREAD

**Issue by vynjo** [redhat-cop/pelorus#39]
When I worked at Circonus I designed executive dashboards which showed year over year, quarter over quarter, etc., graphs to show devops teams 'how are we doing today' kinds of answers. It would be (IMHO) really interesting to show that same thing for each of our 4 key metrics (ALT, Deploy, MRT, CFR).

If interested I'd be happy to contribute, or give more specifics.

**Comment by etsauer** [comment]
@vynjo yes, thats definitely something that we're working on. The first step in this is to come up with a long term storage strategy for our prometheus data.

#23

**Comment by vynjo** [comment]
When I worked at Circonus (now at Red Hat, btw - cmadsen@redhat.com) we always ran into customer dealing with long term Prometheus issues - we came up with IronDB (https://www.circonus.com/solutions/time-series-database/) and a grafana plugin (supporting histograms), and alerting. Pretty cool.

**Comment by vynjo** [comment]
FWIW, a graphana plug/datasource in is https://github.com/circonus-labs/circonus-irondb-datasource.  @kamelkev is incredibly knowledgeable (used to work with him)

**Comment by etsauer** [comment]
resolved by #77
