### ISSUE TITLE
Software Delivery Performance dashboard should be publicly accessible

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pelorus#47]
We would like the resulting dashboard (in read-only mode) to be viewable without having to log in.

**Comment by etsauer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Develop a way to make the dashboard "publicly" accessible](https://trello.com/c/d1rRWynG/68-develop-a-way-to-make-the-dashboard-publicly-accessible)

**Comment by jtudelag** [comment]
@etsauer I am not very experience with Grafana, but after browsing the documentation, it seems ["Anonymous" access can be granted per Organization](https://grafana.com/docs/grafana/latest/auth/overview/#anonymous-authentication).

Applying this to the Pelorus/default org in grafana may work.

**Comment by jtudelag** [comment]
I would say this is already implemented and this issue can be closed.

**Comment by jtudelag** [comment]
Ping @etsauer. I think this is already implemented and can be closed, right?

**Comment by etsauer** [comment]
@jtudelag no, this issue is specific to grafana running in OpenShift (see https://github.com/grafana/grafana/issues/25267). #210 provides a stopgap solution, and still needs review/testing.
