### ISSUE TITLE
Lead Time currently only supports GitHub Repos

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pelorus#51]
Because we are using the GitHub API to grab the commit timestamps, we can currently only support source code on GitHub. Right now the collector code skips repos that don't have `github.com` in the URL, but I would like to find a more generic way to handle grabbing the commit timestamp.

This is more difficult than it sounds, as the only generic way seems to be to clone each repo. I'd like to find some less expensive operation than a full repo clone.

Refactoring to a generic method would also remove a manual step in the install process, where the user has to go generate an API token, which is likely to have scalability problems anyway.

**Comment by springdo** [comment]
For this issue, would a `git clone --bare` be ok? 
It would not be a full repo clone but would give access to the `git log` which could (probably) be parsed to pull out committer id, timestamps etc. Still not as fast as just a straight up api call though

**Comment by dobozysaurus** [comment]
@etsauer @springdo Yep, git clone --bare should work - that's the approach taken on PAM for project repositories.
