### ISSUE TITLE
When executing Helm command you must be in the pelorus namespace

### ISSUE THREAD

**Issue by themoosman** [redhat-cop/pelorus#54]
When executing the Helm commands to create an exporter, you must be in the `pelorus` namespace or the objects will be created in the current namespace.  This occurs even when the `--namespace` command is passed as in `helm template charts/exporter/ -f exporters/failure/values.yaml --namespace pelorus | oc apply -f-`

**Comment by etsauer** [comment]
Reading up on this issue, it seems like the preferred approach is to NOT include the namespace in the templates at all, and pass it via `helm install --namespace pelorus`. Are we ok with that approach?

https://github.com/helm/helm/issues/5465

**Comment by etsauer** [comment]
helm refactor is waiting on https://github.com/operator-framework/community-operators/pull/2120

**Comment by etsauer** [comment]
@themoosman we good to close this? The PR wasn't link so it didn't close automatically.

**Comment by themoosman** [comment]
Yes, this was fixed by #153
