### ISSUE TITLE
Use Helm chart for install instead of an install script

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pelorus#55]
The installation for Pelorus is really just a helm chart, except that we rely on a couple of values in secrets in the monitoring stack in order to wire up pelorus with the openshift monitoring stack.

Since we've done this, we have added a `lookup` function to helm, which could be used to fetch these values as part of processing the chart. https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function

We should switch over to that so that we can get rid of the install script altogether.

**Comment by themoosman** [comment]
Currently blocked by https://github.com/helm/helm/issues/8137

**Comment by sbailleu** [comment]
We are not going to use the "lookup" and actually use the generated password.

**Comment by prakritiverma** [comment]
https://github.com/redhat-cop/pelorus/issues/125

**Comment by prakritiverma** [comment]
#125

**Comment by etsauer** [comment]
This has been completed.
