### ISSUE TITLE
Error: failed to start container

### ISSUE THREAD

**Issue by jon2100** [redhat-cop/pelorus#78]
Running in a disconnected install, changed all image refrances to pull form local quay.
look like everting deploys corerctly but have this error for 
prometheus-prometheus-pelorus-0
prometheus-prometheus-pelorus-1
Error: failed to start container "prometheus-config-reloader": Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "exec: \"/bin/prometheus-config-reloader\": stat /bin/prometheus-config-reloader: no such file or directory"

quaylocal.local/coreos/prometheus-config-reloader:v0.33.0" already present on machine

3.11.153 cluster

**Comment by etsauer** [comment]
@jon2100 sorry for the long lead time on this, we didn't see your issue come in.

That's a strange error, as we don't do anything special with that container image. Have you tried standing up a vanilla prometheus stack using the prometheus operator?

**Comment by jon2100** [comment]
I’ll have to go back and check the bug I may have opened a bz on it

**Comment by etsauer** [comment]
Closing based on our side conversation @jon2100
