### ISSUE TITLE
Modify Deploytime exporter to use Kubernetes standard app label

### ISSUE THREAD

**Issue by themoosman** [redhat-cop/pelorus#95]
Currently, the Deploytime exporter looks for deployments with a label of `application`.  To match the Kubernetes standard, the exporter should look for the label of `app`.  

List of things to change/update:
- Change default label in the exporter code
- Change basic NGINX example to use `app` labels
- Update exporter documentation
- Update Helm chart to allow passing the label as a variable

**Comment by etsauer** [comment]
Document how to set environment variables through helm.
