### ISSUE TITLE
Need a cleaner uninstall process.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pelorus#97]
This is more of a development problem, where we are testing multiple instances of Pelorus in a single cluster. When we follow the documented uninstall process:

```
helm template --namespace pelorus pelorus ./charts/deploy/ | oc delete -f- -n pelorus
```

We end up deleting the operator CRDs, which may still be in use by other instances of pelorus, or other non-pelorus instances of prometheus or grafana. We need a safer way to uninstall the stack, without leaving a bunch of cluster-level rbac resource behind.

**Comment by deweya** [comment]
How's something like this: https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource? You'll have to use `helm uninstall` though and manage the release using install|upgrade|rollback|uninstall as opposed to helm template | oc delete. The annotation can be applied to any resource you don't want to be removed. Or, the label can be generated based on the presence of a value, like `--set keepCRDs=true`.

I can make a PR if you like the approach.

**Comment by etsauer** [comment]
This has been completed.
